name: BOINCStats Scraper

on:
  # Daily at 02:00 UTC
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape BOINCStats
    runs-on: ubuntu-latest

    steps:
      # Checkout current repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run scraper.py script
      - name: Run scraper
        run: |
          mkdir db
          python scraper.py

      # Configure Git for commit
      - name: Configure Git user
        run: |
          git config user.name "${{ secrets.USER }}"
          git config user.email "${{ secrets.EMAIL }}"

      # Commit updated BOINCStats data (only if there are changes)
      - name: Commit BOINCStats data
        run: |
          if [ -d db ] && [ "$(ls -A db)" ]; then
            git add db
            git commit -m "Automatic update of BOINCStats data [GitHub Actions]" || echo "No changes to commit"
            git push
          else
            echo "No db files to commit."
          fi

      # Push changes to the repo's master branch
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }}.git HEAD:master
