name: BOINCStats Scraper

on:
  # Daily at 05:00 UTC (e.g. 07:00 CET/CEST)
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape BOINCStats
    runs-on: ubuntu-latest

    steps:
      # Checkout current repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run scraper.py script
      - name: Run scraper
        run: python scraper.py

      # Configure Git for commit
      - name: Configure Git user
        run: |
          git config user.name "${{ secrets.USER }}"
          git config user.email "${{ secrets.EMAIL }}"

      # Commit updated BOINCStats data (only if there are changes)
      - name: Commit BOINCStats data
        run: |
          git add db/*.txt
          git commit -m "Automatic update of BOINCStats data [GitHub Actions]" || echo "No changes to commit"
          git push

      # Push changes to the repo's master branch
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }}.git HEAD:master
